name: Buil and Deploy

on:
  push:
    branches:
      - main

jobs:
  buuild-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
       uses: actions/setup-node@v2
       with: 
        node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm test

      # - name: Install Dependencies
      #  run: yarn install

      # - name: Build
      #   run: yarn build

      # - name: Upload to FTP
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ server.FTP_USERNAME }}
      #     password: ${{ server.FTP_PASSWORD }}
      #     local-dir: ./dist/
      #     server-dir:
       